### ISSUE TITLE
Error Failed to establish a new connection to login.threefold.me after trying 3bot login

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/3Bot_connect#124]
Error Failed to establish a new connection to `login.threefold.me` 

**How to reproduce**

- Go to staging marketplace and try to do 3bot login: https://marketplace-testnet.grid.tf/

![Screenshot from 2020-08-30 12-33-05](https://user-images.githubusercontent.com/10658229/91656916-f8f86100-eabc-11ea-94c4-8d458af0b276.png)

- Full stacktrace

```bash
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/bin/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/bin/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/root/js-sdk/jumpscale/packages/auth/bottle/auth.py", line 78, in callback
    res = requests.get(f"https://login.threefold.me/api/users/{username}", {"Content-Type": "application/json"})
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/js-sdk-vpmH-Z_5-py3.6/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.threefold.me', port=443): Max retries exceeded with url: /api/users/waleedhammam.3bot?Content-Type=application%2Fjson (Caused by NewConne
ctionError('<urllib3.connection.HTTPSConnection object at 0x7f987eb323c8>: Failed to establish a new connection: [Errno 110] Connection timed out',))
127.0.0.1 - - [2020-08-30 10:27:14] "GET /3bot_callback?signedAttempt=%7B%22signedAttempt%22%3A%222n5LLC1IMHq%2BfxXrukPKF4H725uOP2PqIlEOOr7%2F%2FmXW4AttHpQvimCMglWvVFxrrCzjMT8YDxcTmAmKUxDNAXsic2lnbmVkU3RhdG
UiOiJqeWZzYWJlVFVBVEFJVnlNM2l0YSIsImRhdGEiOnsibm9uY2UiOiJkc2R3cWpBd28wRW9OVEw0Ylp4UDA4emtadjF1bktUMSIsImNpcGhlcnRleHQiOiJYQ0pVeUhqN0pOMnhUTXAwMjBMSC9uUUNLZUg4WFYwcGd3VGVnY1Zlc3cvTUIxVUdIYWlCS2J6N3F5V0M5Mkpu
RFRCTEowREc2VmYyNDdPcEZtVWprbzRWUENRbmdkcy9SL05zcDU4c1VEYndqV1JIMWllU3RnU1ovdjB4eEI5MlhkbncyNDFkem1KL1hxSVcwQ3RQcHYxb0NaVWcvQURFNjJUZWZpZkNNcCsrbS9NSE9mYWV6bFZUcHVLVUJ0SDlBNStFLzgvaFhaeVF3akNxZ25nMzFjVjRwcj
lObVI3V0tVZk52dlNlTVlrSzlkZ0JXV2lKODdMb2JkcDVPeElQYjhBQjNHaHVTTEE5M3lyQktGdzg3QWRHb0pUb0RadnByeE54ZHViT3NvbVhRV1JuaEhQd0llSDAvSWZDbFp2WUhBb2RNRWdaeStTOVI2UHBVUVk9In0sInNlbGVjdGVkSW1hZ2VJZCI6MjI5LCJkb3VibGVO
YW1lIjoid2FsZWVkaGFtbWFtLjNib3QiLCJyYW5kb21Sb29tIjoiMWQ2MzJkN2MtMDQzYy00ZjNmLTk4ZTEtNjViMmExNzJiYTRhIiwiYXBwSWQiOiJtYXJrZXRwbGFjZS10ZXN0bmV0LmdyaWQudGYifQ%3D%3D%22%2C%22doubleName%22%3A%22waleedhammam.3bot%
```

**Comment by jdelrue** [comment]
@MathiasDeWeerdt Can you check?

**Comment by MathiasDeWeerdt** [comment]
https://marketplace-testnet.grid.tf/ seems to be unreachable.

**Comment by jdelrue** [comment]
Was DNS issue, closed
